# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bundesland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundesland', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=20)),
                ('nachname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=5)),
                ('telefon', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.bundesland')),
            ],
        ),
        migrations.AddField(
            model_name='kontakt',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.organisation'),
        ),
    ]
