# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundesland',
            old_name='bundesland',
            new_name='bundeslandname',
        ),
    ]
