# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0003_auto_20161208_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='fax',
        ),
        migrations.AddField(
            model_name='organisation',
            name='stadt',
            field=models.CharField(default='defaultstadt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='strassehsnr',
            field=models.CharField(default='defaultstrasse', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='www',
            field=models.CharField(default='defaultwebsite', max_length=100),
            preserve_default=False,
        ),
    ]
