# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0005_auto_20161210_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesland',
            name='bundesland',
            field=models.CharField(max_length=25, verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Email Adresse'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='nachname',
            field=models.CharField(max_length=20, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='vorname',
            field=models.CharField(max_length=20, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Bundesland'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email Adresse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='plz',
            field=models.CharField(max_length=5, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='stadt',
            field=models.CharField(max_length=50, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='strassehsnr',
            field=models.CharField(max_length=200, verbose_name='Strasse und Hausnummer'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='www',
            field=models.CharField(max_length=100, verbose_name='Homepage'),
        ),
    ]
