# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0007_auto_20170414_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitydate',
            field=models.DateTimeField(verbose_name='Datum der Aktivität'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.ActivityType', verbose_name='Art der Aktivität'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kontakt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Kontakt', verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='titel',
            field=models.CharField(max_length=50, verbose_name='Title der Aktivität'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='editdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Bundesland'),
        ),
    ]
