# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0008_auto_20170419_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationtype', models.CharField(max_length=20, verbose_name='Organisation Type')),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bundesland',
            name='bundeslandshort',
            field=models.CharField(default='BL', max_length=25, verbose_name='Bundesland Short'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='kontakt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Kontakt', verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Bundesland'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisationtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgmgm.OrganisationType'),
            preserve_default=False,
        ),
    ]
