# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-20 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0012_auto_20171018_2153'),
        ('orgmgm', '0012_auto_20180220_2045'),
    ]

    operations = [
    ]
