# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0014_auto_20180220_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='titel',
        ),
        migrations.AddField(
            model_name='kontakt',
            name='anrede',
            field=models.IntegerField(blank=True, choices=[(1, 'Frau'), (2, 'Herr'), (3, 'Sonstige')], null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='rolle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rolle'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telfonnummer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activitydate',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der Aktivität'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgmgm.ActivityType', verbose_name='Art der Aktivität'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='editdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kontakt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Kontakt', verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email Adresse'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Organisation'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='vorname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgmgm.Bundesland'),
        ),
    ]
