# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-21 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0015_auto_20180221_1954'),
        ('orgmgm', '0015_merge_20180220_2222'),
    ]

    operations = [
    ]
