# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-21 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgmgm', '0016_merge_20180221_2006'),
        ('orgmgm', '0016_auto_20180221_2232'),
    ]

    operations = [
    ]
